# Generated by Django 4.0.3 on 2022-03-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('userImage', models.ImageField(upload_to='uploads/')),
                ('postImage', models.ImageField(upload_to='uploads/')),
                ('likes', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('liked', models.BooleanField(default=False)),
                ('content', models.TextField(max_length=255)),
                ('filter', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
